services:
  api-gateway:
    container_name: api-gateway
    image: nginx:alpine
    depends_on:
      - auth-service
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-network

  
  # Auth Service
  auth-service:
    container_name: auth-service
    image:
      deploy:
        recources:
          limits:
            cpu: "0.5"
            memory: 512M
    build: ./auth-service
    depends_on:
      - auth-db
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGO_URI: mongodb://auth-db:27017/auth
      JWT_SECRET: "cc25a4c7e191b5f12ebcb8f7"
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    networks:
      - microservices-network

  
  # Auth Database
  auth-db:
    container_name: auth-db
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - auth-data:/data/db
    networks:
      - microservices-network

  
  # Acad Service
  acad-service:
    container_name: acad-service
    build: ./acad-service
    depends_on:
      - acad-db
    environment:
      DB_HOST: acad-db
      DB_PORT: 5432
      DB_NAME: products
      DB_USER: productuser
      DB_PASSWORD: productpass
    ports:
      - "3002:3002"
    networks:
      - microservices-network

  
  # Acad DB
  acad-db:
    container_name: acad-db
    image: postgres:15
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: productpass
    ports:
      - "5432:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/28

volumes:
  auth-data:
  product-data:
  order-data: